import { cp, mkdir, rm } from 'node:fs/promises';

await rm('public', { recursive: true, force: true });
await mkdir('public/client', { recursive: true });
await mkdir('public/data', { recursive: true });
await mkdir('public/domain', { recursive: true });
await mkdir('public/shared', { recursive: true });
await cp('src/client/index.html', 'public/index.html');
await cp('src/client/manifest.webmanifest', 'public/manifest.webmanifest');
await cp('src/client/icon.svg', 'public/icon.svg');
await cp('src/client/sw.js', 'public/sw.js');
await cp('src/client/styles.css', 'public/client/styles.css');
await cp('src/client/app.js', 'public/client/app.js');
await cp('src/client/auth.js', 'public/client/auth.js');
await cp('src/client/realtime.js', 'public/client/realtime.js');
await cp('src/client/workflows.js', 'public/client/workflows.js');
await cp('src/data/local-repository.js', 'public/data/local-repository.js');
await cp('src/data/remote-repository.js', 'public/data/remote-repository.js');
await cp('src/domain/scheduler.js', 'public/domain/scheduler.js');
await cp('src/domain/tables.js', 'public/domain/tables.js');
await cp('src/domain/commands.js', 'public/domain/commands.js');
await cp('src/shared/contracts.js', 'public/shared/contracts.js');
